# Generated by Django 5.1.6 on 2025-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('community', 'Community'), ('key-access', 'Key Access'), ('creative-workspace', 'Creative Workspace')], max_length=50),
        ),
    ]
