# Generated by Django 5.1.6 on 2025-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_ongoingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('Community', 'Community'), ('Key Access', 'Key Access'), ('Creative Workspace', 'Creative Workspace')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
