# Generated by Django 5.1.6 on 2025-03-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
